### ISSUE TITLE
cloudsmith upload raw fails due to unknown architecture

### ISSUE THREAD

**Issue by reubenmiller** [cloudsmith-io/cloudsmith-cli#155]
It seems that an upgrade in the `cloudsmith-api` dependency to `2.0.8` causes an uploading of a raw package via `cloudsmith upload raw` to fail due to ```ValueError: Invalid value for `architecture` (dummy)``` error, which would suggest that the raw package now needs its architecture defined, however the cloudsmith-cli version does not provide an option for specifying this.

The [cloudsmith-api was recently released](https://pypi.org/project/cloudsmith-api/2.0.8/#history) which breaks this due to only be a patch release, which means it was pulled in automatically by `cloudsmith-cli`.

Below shows two examples of using the previous (working) version of cloudsmith-api 2.0.7 and the newer version 2.0.8.

**OK - Using cloudsmith-cli 1.1.1 with cloudsmith-api 2.0.7**

Installing cloudsmith-cli:

```
$ pip3 install --upgrade cloudsmith-cli
Successfully installed certifi-2024.2.2 charset-normalizer-3.3.2 click-8.1.7 click-configfile-0.2.3 click-didyoumean-0.3.0 click-spinner-0.1.10 cloudsmith-api-2.0.7 cloudsmith-cli-1.1.1 configparser-6.0.0 idna-3.6 python-dateutil-2.8.2 requests-2.31.0 requests-toolbelt-1.0.0 semver-3.0.2 six-1.16.0 urllib3-1.26.18
```

Uploading a raw binary:

```
cloudsmith upload raw ***/tedge-main tmp/tedge.tar.gz --name tedge-amd64 --version 1.0.1-rc37+g6f6f603 --no-wait-for-sync --api-key ***
Uploading file: target/x86_64-unknown-linux-musl/packages/tedge_1.0.1-rc37+g6f6f603_x86_64-unknown-linux-musl.tar.gz (name=tedge-amd64, version=1.0.1-rc37+g6f6f603, file=tmp/tedge.tar.gz)
```

**FAIL - Using cloudsmith-cli 1.1.1 with cloudsmith-api 2.0.8**

Installing cloudsmith-cli:

```sh
$ pip3 install --upgrade cloudsmith-cli
Successfully installed certifi-2024.2.2 charset-normalizer-3.3.2 click-8.1.7 click-configfile-0.2.3 click-didyoumean-0.3.0 click-spinner-0.1.10 cloudsmith-api-2.0.8 cloudsmith-cli-1.1.1 configparser-6.0.0 idna-3.6 python-dateutil-2.8.2 requests-2.31.0 requests-toolbelt-1.0.0 semver-3.0.2 six-1.16.0 urllib3-1.26.18
```

Uploading a raw binary:

```log
cloudsmith upload raw ***/tedge-main tmp/tedge.tar.gz --name tedge-amd64 --version 1.0.1-rc51+g3389918 --no-wait-for-sync --api-key ***
Uploading file: target/x86_64-unknown-linux-musl/packages/tedge_1.0.1-rc51+g3389918_x86_64-unknown-linux-musl.tar.gz (name=tedge-amd64, version=1.0.1-rc51+g3389918, file=tmp/tedge.tar.gz)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.8/x64/bin/cloudsmith", line 5, in <module>
    from cloudsmith_cli.cli.commands.main import main
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/cloudsmith_cli/cli/commands/__init__.py", line 3, in <module>
    from . import (
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/cloudsmith_cli/cli/commands/copy.py", line 10, in <module>
    from .push import wait_for_package_sync
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/cloudsmith_cli/cli/commands/push.py", line 568, in <module>
    create_push_handlers()
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/cloudsmith_cli/cli/commands/push.py", line 420, in create_push_handlers
    context = create_push_handlers.context = get_package_formats()
                                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/cloudsmith_cli/core/api/packages.py", line 274, in get_package_formats
    return {
           ^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/cloudsmith_cli/core/api/packages.py", line 275, in <dictcomp>
    key.replace("PackageUploadRequest", "").lower(): get_parameters(cls)
                                                     ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/cloudsmith_cli/core/api/packages.py", line 251, in get_parameters
    instance = cls(**dummy_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/cloudsmith_api/models/cran_package_upload_request.py", line 65, in __init__
    self.architecture = architecture
    ^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/cloudsmith_api/models/cran_package_upload_request.py", line 97, in architecture
    raise ValueError(
ValueError: Invalid value for `architecture` (dummy), must be one of ['arm64', 'x86_64']
```

**Comment by galonsky** [comment]
we are seeing the same issue this morning. problematic since the circle ci orb (https://circleci.com/developer/orbs/orb/cloudsmith/cloudsmith) installs the latest versions

**Comment by alexborro** [comment]
Same issue here. All our CI pipelines are blocked from uploading packages to cloudsmith because they use the action `cloudsmith-io/action@master`

![image](https://github.com/cloudsmith-io/cloudsmith-cli/assets/5216531/5a05cb4f-c891-4ca0-abe1-754ca81c60a8)

**Comment by rickscarta** [comment]
Related, the cloudsmith_api just bumped the version: https://github.com/cloudsmith-io/cloudsmith-api/pull/48

diff between my pipeline that ran yesterday successfully and today's that failed:
 - success: cloudsmith_api-2.0.7
 - failed: cloudsmith_api-2.0.8

**Comment by reubenmiller** [comment]
**Workaround**

If you're installing cloudsmith-cli via pip (e.g. not using the github action), then you can control the version of the cloudsmith-api by specifying the version using pip requirements file, for example:

```sh
#!/bin/bash

# Install cloudsmith-cli but control cloudsmith-api version
# due to https://github.com/cloudsmith-io/cloudsmith-cli/issues/155
pip3 install -r <(
        cat << EOT
cloudsmith-cli==1.1.1
cloudsmith-api==2.0.7
EOT
)

# Then call cloudsmith upload raw as before
cloudsmith upload raw ./tedge-main tmp/tedge.tar.gz --name tedge-amd64 --version 1.0.1-rc37+g6f6f603 --no-wait-for-sync --api-key ***
```

**Comment by galonsky** [comment]
they pulled cloudsmith-api 2.0.8 so this should be resolved for now

**Comment by reubenmiller** [comment]
> they pulled cloudsmith-api 2.0.8 so this should be resolved for now

I can confirm that with cloudsmith-api 2.0.8 being yanked, that publishing of the raw packages now works again :)

Thanks cloudsmith team for the quick response time, much appreciated!

**Comment by jackgibson1** [comment]
Hey folks 👋 , thanks for reporting the issue! Sorry for the bug!

I'm an engineer at Cloudsmith. Unfortunately as you noticed, we released a broken version of the `cloudsmith-api` (a wrapper around our API). This release was incompatible with our CLI, causing the error you guys saw. We changed some logic around enum-values that broke the cli.

As you've seen, the impacted release was been yanked. So you should be good already.

We'll ship a change on our end to make `v2.0.9` fully compatible so this doesn't happen again. Again, apologies for the inconvenience!
