### ISSUE TITLE
Default credentials file in `~/.cloudsmith/credentials.ini` is ignored

### ISSUE THREAD

**Issue by Veetaha** [cloudsmith-io/cloudsmith-cli#73]
I added a file with the following contents:
```ini
# Default configuration
[default]
api_key={redacted}
```
However, it doesn't work for me if this file is located in `${HOME}/.cloudsmith/credentials.ini`, the CLI still sees me as an anonymous user.
If I move that file to `${HOME}/.config/credentials.ini`, then everything works fine.

## Meta
I am using a server via SSH, my environment is the following:

```
$ uname -a
Linux veetaha-hetzner 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dmeecs** [comment]
Hi @Veetaha  thanks for opening this. We think we've got a fix for this issue at https://github.com/cloudsmith-io/cloudsmith-cli/pull/79 

Once it's merged will make a release so this problem ought to go away for you.
